### ISSUE TITLE
Render issue with Create's Netherite Backtank

### ISSUE THREAD

**Issue by TheStaticVoid** [tr7zw/3d-Skin-Layers#121]
Modlist:
- Create Fabric 0.5.1b
- Fabric API 0.76.0
- Skin Layers 3d 1.5.2

Loader:
- Fabric 0.14.21
- Minecraft 1.19.2

With this mod setup, equipping the Netherite Backtank will cause the hand model in first person to disappear.
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/6089108/cf11153f-6785-4bba-b6c5-580d07966570)
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/6089108/dc652958-c81f-4f5d-89fa-69b5c6fd37fd)

**Comment by elenawinters** [comment]
Pretty sure this happens because Create cancels the onRenderPlayerHand event, at least on Forge. This has been a known issue.

Unlikely to be an issue with this mod.

Relevant Forge Create code: https://github.com/Creators-of-Create/Create/blob/mc1.19/0.5.1/src/main/java/com/simibubi/create/content/equipment/armor/NetheriteBacktankFirstPersonRenderer.java

Relevant Fabric Create code: https://github.com/Fabricators-of-Create/Create/blob/mc1.19/fabric/dev/src/main/java/com/simibubi/create/content/equipment/armor/NetheriteBacktankFirstPersonRenderer.java

**Comment by tr7zw** [comment]
Yea, removing the entire arm is nothing this mod could do, at worst hide the vanilla 2d layer and then not render the 3d one. So its unrelated.
