### ISSUE TITLE
3D Skin Layers 1.6.2-1.17.1 incompatable with Fabric API 0.46.1+1.17, when it shouldnt be.

### ISSUE THREAD

**Issue by TheD0ct0r101** [tr7zw/3d-Skin-Layers#149]
For whatever reason jumping from 1.6.1 to 1.6.2 causes the game to not run even when using the latest release-version of fabric api for 1.17.1.

![image](https://github.com/tr7zw/3d-Skin-Layers/assets/11579139/ae27c540-b270-4c9f-9b13-f612504b0077)

![image](https://github.com/tr7zw/3d-Skin-Layers/assets/11579139/66f2d64b-afc6-4b3d-82a6-f26d925c9c7e)

**Comment by tr7zw** [comment]
Ehhhh because 1.17 fabric-api has a bug, and doesn't know that it is called "fabric-api", instead thinking it's "fabric". This will affect all of my mods that have 1.17 versions, but since no one reported that for 5+ months, it's safe to assume 1.17 is 100% dead. I just have these builds as a byproduct of having a 1.16 and a 1.18 version. I'll fix it for the next release, but you really should consider updating to 1.18(or better higher) or down to 1.16. 1.17 won't get any fixes/updates/new mods from most devs.

**Comment by tr7zw** [comment]
Just noticed that it already is fixed, there just hasn't been a 3d skin layers release since the fix. Either way, worst case when 1.20.5 releases this will get a fixed release.

**Comment by TheD0ct0r101** [comment]
> Ehhhh because 1.17 fabric-api has a bug, and doesn't know that it is called "fabric-api", instead thinking it's "fabric". This will affect all of my mods that have 1.17 versions, but since no one reported that for 5+ months, it's safe to assume 1.17 is 100% dead. I just have these builds as a byproduct of having a 1.16 and a 1.18 version. I'll fix it for the next release, but you really should consider updating to 1.18(or better higher) or down to 1.16. 1.17 won't get any fixes/updates/new mods from most devs.

Sadly the custom map im hosting on my modded server is locked to 1.17.1 due to mojang revamping the biome system between 1.17 and 1.18 (all old biomes technically got deleted and refactored) so until the devs of the map port the map to 1.20 im essentially trapped lmao
