### ISSUE TITLE
1.18.2 3D Skull Items Be Set to "Off" by Defualt 

### ISSUE THREAD

**Issue by Th3LastSh3riff** [tr7zw/3d-Skin-Layers#47]
May you make the defualt option to "3D skull items" be set to "Off," in some servers the 3D skull items do not render in correctly and cause either the game to crash or cause your FPS to drop. The only known way to fix this is by setting "3D skull items" to "Off" before entering a server.

**Comment by tr7zw** [comment]
I think turning a major feature off because of basically one server(that I am aware of, OriginRealms) is a bit unreasonable for everyone else. I am open for detecting ways that this is going on and then auto disabling it, the issue with that is that all of this is done in vanilla shaders, so no clue how to detect that. I guess another bandaid kind of way could be hardcoding servers to disable the feature. For now the official solution is to just turn it off yourself. Future tracking in #45
