### ISSUE TITLE
Damage Tint Not Applied to 3D Skin Layer

### ISSUE THREAD

**Issue by AwkwardAiden** [tr7zw/3d-Skin-Layers#65]
Not sure if this issue has been submitted before, there's one thats similar but not my problem. I'm also not sure if it's due to me using Feather Client instead of something else, I don't think that's the issue since Feather runs off of fabric anyways.

Whenever damage is taken, the 3D rendered part of the skin from this mod stays the same color instead of changing color with the rest of the skin. I'm not sure if it's not possible for this to be added or if it's a bug on my end, but it would make the mod a lot better.
![2022-06-02_22 21 35](https://user-images.githubusercontent.com/96404187/171774739-444930a3-3e1b-467c-a24e-a67f8a998055.png)
![2022-06-02_22 21 00](https://user-images.githubusercontent.com/96404187/171774740-549488cd-db24-48ad-8baf-f9472f6413c9.png)

**Comment by tr7zw** [comment]
Currently the tint is using a workaround that just redshifts the color( see #26 ). Due to the hair being black, red shifting black is still black so it looks like nothing happened. After a rework to inject the layers into the model itself this is probably fixed, but might cause other issues with other mods.
