### ISSUE TITLE
NPE when getting skin texture

### ISSUE THREAD

**Issue by Insprill** [tr7zw/3d-Skin-Layers#76]
When playing on Hypixel, I noticed my log is spammed full of null pointers when trying to get skin textures.

Error: https://pastebin.com/Mu9WzY59

Mods (Fabric):
- 3D Skin Layers - 1.4.7
- Better F3
- Continuity
- Carpet
- Indium
- Iris
- Lithium
- Logical Zoom
- Shulker Box Tooltip
- Sodium
- Starlight

I would've attempted to fix it in a PR but there's no documentation on setting up the build system and I haven't worked with it before as it seems custom 😅

**Comment by tr7zw** [comment]
The build system is just gradle, but with a ``c``(``gradlecw``) in there(for composing, like docker-compose). It spawns the gradle build files out of a template to help maintain updated dependencies, change the build across all my mods, and simplify updating mc. 
And yea I noticed these NPE's too, my guess is that Hypixel sends some custom/corrupted head or npc data? I haven't yet looked into the code to check the exact cause, since it doesn't seem to cause direct issues.

**Comment by Insprill** [comment]
Ah, I see how it works now. Thank you!
I did a very small amount of digging and in `HttpTextureMixin` the file doesn't exist which seems to be the cause of the errors. I haven't done much fabric modding so I can't really help more than that code wise, unfortunately.

**Comment by tr7zw** [comment]
Huh that's odd, why wouldn't it exist but be loaded 🤔. Currently a bit busy getting https://github.com/tr7zw/FasterGUI into a production-ready state. Guess I'll look at this next time I work on this mod.
