### ISSUE TITLE
Should be  flagged as client only

### ISSUE THREAD

**Issue by ZEROX7** [tr7zw/3d-Skin-Layers#87]
would it be possible to make it falgged as client only so if its installed on a server it wont be loaded and the crash will not happen?

**Comment by tr7zw** [comment]
That's a Forge issue, they removed the concept of "Client mods" and didn't provide any replacement. Just one more reason to stop using it.

**Comment by ZEROX7** [comment]
there still is a way to do it other mods do it too, and if you dont like forge then dont support it, its your mod you can choose waht to support but if you do you should do it all the way.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/3d-Skin-Layers/blob/1.19/3dSkinLayers-Forge/src/main/java/dev/tr7zw/skinlayers/SkinLayersMod.java#L20
I do try to catch it, but it's a stupid hack and doesn't work all the time due to other fields in the class. There used to be "side=client" flag in the toml, but that apparently got removed some time ago without any replacement. If you have a link to how it's supposed to be done now please share it, because the forge docs are a mess.
*Cut out some rant about forge, tldr: Fabric is more important*
Updated https://tr7zw.github.io/versions/ to better reflect that.

**Comment by tr7zw** [comment]
Added in 1.6.0.
