### ISSUE TITLE
Emissive Textures Don't Work When Using ETF

### ISSUE THREAD

**Issue by TrueVenomized** [tr7zw/3d-Skin-Layers#93]
ETF (Entity Texture Features) has an option for emissive textures on player skins. When using 3d Skin Layers, the emissive texture doesn't work on the 3d skin layers. It works again if you disable the 3d-ness.
I have also submitted an issue on the ETF Github
ETF Github: https://github.com/Traben-0/Entity_Texture_Features

**Comment by tr7zw** [comment]
I'll straight up say, probably no fix from my end. Using emissive textures on a player is really niche, and in the past, I just had a horrible experience with Optifine's emissive implementation.
In case the ETF dev reads this, I have made an API to get the 3d mesh (https://github.com/tr7zw/3d-Skin-Layers/blob/1.19.3/Shared/src/main/java/dev/tr7zw/skinlayers/api/MeshProvider.java#L14) and rendering it using your own vertex consumer, etc (https://github.com/tr7zw/3d-Skin-Layers/blob/1.19.3/Shared/src/main/java/dev/tr7zw/skinlayers/api/Mesh.java#L12), so that might help. https://github.com/tr7zw/3d-Skin-Layers/blob/1.19.3/Shared/src/main/java/dev/tr7zw/skinlayers/api/SkinLayersAPI.java#L19 There is also a mesh method, to generate the mesh using your own texture. If required, I can provide an event handler to the correct point in time to render extra layers, including the data to render it in the right place.

**Comment by Traben-0** [comment]
That looks like something I can work with, I'll be looking into this tomorrow

**Comment by Traben-0** [comment]
this has been resolved in ETF release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0
